FROM mcr.microsoft.com/dotnet/sdk:9.0 AS final
WORKDIR /src
EXPOSE 8080
ENV ASPNETCORE_ENVIRONMENT=Development
ENV ASPNETCORE_URLS=http://+:8080
CMD ["dotnet", "watch", "run", "--project", "src/WLR.API/WLR.API.csproj"]
